version: '3.8'

networks:
  app-net:

services:
  mysql:
    image: mysql:8.0
    container_name: app-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: demo_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-net

  redis:
    image: redis:7-alpine
    container_name: app-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --requirepass redis123~~~
    networks:
      - app-net

  app:
    build: .
    container_name: sqq-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: demo_db
      DB_USER: root
      DB_PWD: root123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PWD: redis123~~~
    networks:
      - app-net