server:
  port: ${SERVER_PORT:8089}
  error:
    path: /error
  servlet:
    session:
      timeout: 60
  tomcat:
    max-threads: 250
    uri-encoding: UTF-8

spring:
  messages:
    basename: i18n/messages
    cache-duration: 3600
    encoding: UTF-8

  mvc:
    static-path-pattern: /static/**

  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**

  datasource:
    url: jdbc:mysql://${DB_HOST:172.24.17.63}:${DB_PORT:3306}/${DB_NAME:demo_db}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PWD:root123456}
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:172.24.17.63}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:redis123~~~}

mybatis:
  type-aliases-package: com.sqq.domain
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.sqq.util.MyMapper
  not-empty: false
  identity: MYSQL